run_id: run-11

data_dir: data
fold_id: 0

arch: BengaliSEResNeXt50NS

n_epoch: 30
batch_size: 96
input_size: 128

loss_type: ce   # ce | ohem
pooling_type: gap   # gap | gemp
scheduler_type: rop   # cosanl | rop

cutmix_prob: 0
feat_dim: 512