run_id: run-21

data_dir: data
fold_id: 0

arch: BengaliResNet34NS
use_maxblurpool: True

n_epoch: 50
#batch_size: 96
batch_size: 140
n_iter_per_epoch: 1700
input_size: 224
lr: 0.001
freeze_bn_epochs:
  - 49
  - 50

loss_type: ce   # ce | ohem
pooling_type: gap   # gap | gemp
optimizer_type: sgd   # sgd | adam | ranger
scheduler_type: rop   # cosanl | rop
augmentor_type: v1    # v1
sampler_type: random

use_augmentor: true
cutmix_prob: 0.5
feat_dim: 128

rop_patience: 4
rop_factor: 0.1