run_id: run-7

data_dir: data
fold_id: 0

arch: BengaliSEResNeXt50

n_epoch: 30
batch_size: 96
input_size: 128

loss_type: ohem   # ce | ohem
pooling_type: gemp   # gap | gemp
scheduler_type: rop   # cosanl | rop

cutmix_prob: 0.5