run_id: run-91

data_dir: data
fold_id: 0

arch: BengaliResNet34V4
#arch: BengaliSEResNeXt50V4
n_channel: 3
use_maxblurpool: True
remove_last_stride: True

n_epoch: 100
#batch_size: 64  # SEResNeXt50
batch_size: 128  # ResNet34
#batch_size: 128
#batch_size: 196
#batch_size: 256
batch_p: 32
batch_k: 2
n_iter_per_epoch: 1700
#n_iter_per_epoch: 800
n_low_freq_samples: 8
n_class_low_freq: 80

#input_size: 224
input_size: 128

input_size_tuple:
  - 137
  - 236

#lr: 0.0002
lr: 0.001
#lr: 0.01

#freeze_bn_epochs:
#  - 49
#  - 50

loss_type_g: ohem   # ce | weighted_ce | ohem | focal | reduced_focal
loss_type_v: ohem   # ce | weighted_ce | ohem | focal | reduced_focal
loss_type_c: ohem   # ce | weighted_ce | ohem | focal | reduced_focal

loss_type_feat_g: af
loss_type_feat_v: af
loss_type_feat_c: af

feat_loss_weight: 0.1

pooling_type: gemp   # gap | gemp
optimizer_type: radam   # sgd | adam | ranger | radam
scheduler_type: rop   # cosanl | rop
augmentor_type: v3    # v1 | v2 | v3
sampler_type: random+append  # random | random+append | pk

use_augmentor: true
cutmix_prob: 0.25
mixup_prob: 0.25
feat_dim: 128

rop_patience: 4
#rop_patience: 2
#rop_factor: 0.5
rop_factor: 0.1

cosanl_t_mult: 2

enable_random_morph: True
invert_color: True

af_scale_g: 8
af_scale_v: 3
af_scale_c: 3


# MEMO
# ----
# 
# - batch_size
# - 3 channel (x.repeat(1, 3, 1, 1))
# - SGD lr=0.1
# - SEResNeXt50
# - imbalance data