run_id: run-34

data_dir: data
fold_id: 0

#arch: BengaliResNet34JPUNS3
arch: BengaliResNet34
use_maxblurpool: True
remove_last_stride: True

n_epoch: 50
#batch_size: 96
#batch_size: 140
batch_size: 196
#batch_size: 256
batch_p: 128
batch_k: 2
#n_iter_per_epoch: 1700
n_iter_per_epoch: 800
#input_size: 224
input_size: 128
lr: 0.001
#lr: 0.01
freeze_bn_epochs:
  - 49
  - 50

loss_type_g: weighted_ce   # ce | weighted_ce | ohem | focal | reduced_focal
loss_type_v: weighted_ce   # ce | weighted_ce | ohem | focal | reduced_focal
loss_type_c: weighted_ce   # ce | weighted_ce | ohem | focal | reduced_focal

pooling_type: gemp   # gap | gemp
optimizer_type: ranger   # sgd | adam | ranger
scheduler_type: rop   # cosanl | rop
augmentor_type: v2    # v1
sampler_type: random  # random | pk

use_augmentor: true
cutmix_prob: 0.5
feat_dim: 128

#rop_patience: 4
rop_patience: 3
rop_factor: 0.1

enable_random_morph: True