run_id: run-17

data_dir: data
fold_id: 0

arch: BengaliResNet34

n_epoch: 80
#batch_size: 96
batch_size: 128
n_iter_per_epoch: 1700
input_size: 224

loss_type: ce   # ce | ohem
pooling_type: gap   # gap | gemp
scheduler_type: rop   # cosanl | rop
augmentor_type: v1    # v1
sampler_type: random

use_augmentor: true
cutmix_prob: 0.5
feat_dim: 128