run_id: run-44

data_dir: data
fold_id: 0

#arch: BengaliResNet34JPUNS3
#arch: BengaliResNet34V2
arch: BengaliResNet34V3
#arch: BengaliResNet34NS
n_channel: 3
use_maxblurpool: True
remove_last_stride: True

n_epoch: 50
#batch_size: 96
batch_size: 128
#batch_size: 196
#batch_size: 256
batch_p: 128
batch_k: 2
#n_iter_per_epoch: 1700
n_iter_per_epoch: 800
n_low_freq_samples: 10

#input_size: 224
input_size: 128
lr: 0.0002
#lr: 0.001
#lr: 0.01
freeze_bn_epochs:
  - 49
  - 50

loss_type_g: ce   # ce | weighted_ce | ohem | focal | reduced_focal
loss_type_v: ce   # ce | weighted_ce | ohem | focal | reduced_focal
loss_type_c: ce   # ce | weighted_ce | ohem | focal | reduced_focal

loss_type_feat_g: ns
loss_type_feat_v: ns
loss_type_feat_c: ns

pooling_type: gemp   # gap | gemp
optimizer_type: ranger   # sgd | adam | ranger
scheduler_type: rop   # cosanl | rop
augmentor_type: v3    # v1 | v2 | v3
sampler_type: random+append  # random | random+append | pk

use_augmentor: true
cutmix_prob: 0
feat_dim: 128

#rop_patience: 4
rop_patience: 2
rop_factor: 0.5
#rop_factor: 0.1

enable_random_morph: True
invert_color: True


# MEMO
# ----
# 
# - batch_size
# - 3 channel (x.repeat(1, 3, 1, 1))
# - SGD lr=0.1
# - SEResNeXt50
# - imbalance data